version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis (includes gosimple)
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - revive        # Golint replacement
    - gocritic      # Comprehensive Go source code linter
    - gocyclo       # Check cyclomatic complexity
    - gosec         # Security checks
    - unconvert     # Remove unnecessary type conversions
    - dupl          # Check for duplicate code
    - prealloc      # Find slice declarations that could be pre-allocated
    - nolintlint    # Reports ill-formed or insufficient nolint directives

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      settings:
        shadow:
          strict: true

    gocyclo:
      min-complexity: 15

    dupl:
      threshold: 100

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - unnecessaryBlock

    misspell:
      locale: US

    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: var-naming
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false

    gosec:
      excludes:
        - G104 # Audit errors not checked - we use errcheck for this

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec
          - errcheck

      # Exclude known linters from partially hard-vendored code
      - path: vendor/
        linters:
          - all

      # Exclude some staticcheck messages
      - linters:
          - staticcheck
        text: "SA1019:" # Ignore deprecation warnings

      # Exclude package comment requirement for main
      - path: main\.go
        linters:
          - revive
        text: "package-comments"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
